prediction_sampling: # prediction sampling interval (in seconds)
  60
ls_thres_pass: # threshold on lineage score for passing
  0.5
ss_thres_Shiconf: # threshold on susceptibility score for high-confidence susceptibility
  0.6
ss_thres_SR: # threshold on susceptibility score for susceptibility
  0.5
ss_thres_Rhiconf: # threshold on susceptibility score for high-confidence non-susceptibility
  0.4
mimic_ont_mbp_per_minute: # mimic-ont; milions of basepairs per minute
 "1.43"
mimic_ont_datetime: # mimic-ont; date time of the sequencing start
 "2018-01-01 00:00:00"
